import { ArrowLeft, FileText, Shield, AlertTriangle, Scale, BookOpen, CheckCircle } from 'lucide-react';
import { useLanguage } from '../context/LanguageContext';

interface TermsOfUsePageProps {
  onBack: () => void;
  onNavigate?: (page: 'privacy' | 'disclaimer') => void;
}

export default function TermsOfUsePage({ onBack, onNavigate }: TermsOfUsePageProps) {
  const { t } = useLanguage();
  const lastUpdated = "January 2025";

  return (
    <div className="min-h-screen bg-[#fafaf9] flex flex-col">
      {/* Header */}
      <header className="bg-white border-b-2 border-black">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 py-4 sm:py-6">
          <button
            onClick={onBack}
            className="flex items-center gap-2 text-gray-600 hover:text-black transition-colors mb-4"
          >
            <ArrowLeft className="w-4 h-4" />
            <span className="text-sm sm:text-base">Back to Dashboard</span>
          </button>
          <div className="flex items-center gap-3">
            <div className="p-2 sm:p-3 bg-blue-100 rounded-xl border-2 border-black">
              <FileText className="w-6 h-6 sm:w-8 sm:h-8 text-blue-600" />
            </div>
            <div>
              <h1 className="text-2xl sm:text-3xl font-bold">Terms of Use</h1>
              <p className="text-xs sm:text-sm text-gray-500">Last updated: {lastUpdated}</p>
            </div>
          </div>
        </div>
      </header>

      {/* Main Content */}
      <main className="flex-1 max-w-4xl mx-auto px-4 sm:px-6 py-6 sm:py-8">
        {/* Important Notice Banner */}
        <div className="bg-amber-50 border-2 border-amber-400 rounded-xl p-4 sm:p-6 mb-6 sm:mb-8">
          <div className="flex items-start gap-3">
            <AlertTriangle className="w-6 h-6 text-amber-600 flex-shrink-0 mt-0.5" />
            <div>
              <h2 className="font-bold text-amber-800 text-base sm:text-lg">Important Notice</h2>
              <p className="text-amber-700 text-sm sm:text-base mt-1">
                By using BTEC Generator, you acknowledge that you have read, understood, and agree to be bound by these Terms of Use. 
                If you do not agree with any part of these terms, you must not use this service.
              </p>
            </div>
          </div>
        </div>

        {/* Terms Sections */}
        <div className="space-y-6 sm:space-y-8">
          {/* Section 1: Purpose of Service */}
          <section className="bg-white border-2 border-black rounded-xl p-4 sm:p-6 shadow-[4px_4px_0px_0px_rgba(0,0,0,1)]">
            <div className="flex items-center gap-3 mb-4">
              <div className="p-2 bg-blue-100 rounded-lg border-2 border-black">
                <BookOpen className="w-5 h-5 text-blue-600" />
              </div>
              <h2 className="text-lg sm:text-xl font-bold">1. Purpose of Service</h2>
            </div>
            <div className="space-y-3 text-gray-700 text-sm sm:text-base">
              <p>
                BTEC Generator is designed as an <strong>educational assistance tool</strong> to help students understand 
                assignment structures, develop their writing skills, and learn how to approach BTEC coursework effectively.
              </p>
              <p>
                This platform provides <strong>reference materials, examples, and guidance</strong> that students can use 
                to inform their own original work. The content generated by this service is intended to serve as a 
                <strong> learning resource and starting point</strong>, not as final submissions.
              </p>
              <div className="bg-blue-50 border border-blue-200 rounded-lg p-3 sm:p-4 mt-4">
                <p className="text-blue-800 text-sm">
                  <strong>Key Point:</strong> Our service helps you understand what good coursework looks like and how to 
                  structure your assignments. Use this knowledge to create your own original work.
                </p>
              </div>
            </div>
          </section>

          {/* Section 2: User Responsibilities */}
          <section className="bg-white border-2 border-black rounded-xl p-4 sm:p-6 shadow-[4px_4px_0px_0px_rgba(0,0,0,1)]">
            <div className="flex items-center gap-3 mb-4">
              <div className="p-2 bg-purple-100 rounded-lg border-2 border-black">
                <Shield className="w-5 h-5 text-purple-600" />
              </div>
              <h2 className="text-lg sm:text-xl font-bold">2. User Responsibilities</h2>
            </div>
            <div className="space-y-3 text-gray-700 text-sm sm:text-base">
              <p>As a user of BTEC Generator, you agree to the following:</p>
              <ul className="space-y-2 ml-4">
                <li className="flex items-start gap-2">
                  <CheckCircle className="w-4 h-4 text-green-600 flex-shrink-0 mt-1" />
                  <span>You will use generated content <strong>only as a reference or study aid</strong></span>
                </li>
                <li className="flex items-start gap-2">
                  <CheckCircle className="w-4 h-4 text-green-600 flex-shrink-0 mt-1" />
                  <span>You will <strong>not submit generated content directly</strong> as your own work</span>
                </li>
                <li className="flex items-start gap-2">
                  <CheckCircle className="w-4 h-4 text-green-600 flex-shrink-0 mt-1" />
                  <span>You understand that <strong>academic honesty is your responsibility</strong></span>
                </li>
                <li className="flex items-start gap-2">
                  <CheckCircle className="w-4 h-4 text-green-600 flex-shrink-0 mt-1" />
                  <span>You will comply with your institution's <strong>academic integrity policies</strong></span>
                </li>
                <li className="flex items-start gap-2">
                  <CheckCircle className="w-4 h-4 text-green-600 flex-shrink-0 mt-1" />
                  <span>You are at least <strong>16 years of age</strong> or have parental/guardian consent</span>
                </li>
              </ul>
            </div>
          </section>

          {/* Section 3: Acceptable Use */}
          <section className="bg-white border-2 border-black rounded-xl p-4 sm:p-6 shadow-[4px_4px_0px_0px_rgba(0,0,0,1)]">
            <div className="flex items-center gap-3 mb-4">
              <div className="p-2 bg-green-100 rounded-lg border-2 border-black">
                <CheckCircle className="w-5 h-5 text-green-600" />
              </div>
              <h2 className="text-lg sm:text-xl font-bold">3. Acceptable Use</h2>
            </div>
            <div className="space-y-4 text-gray-700 text-sm sm:text-base">
              <div>
                <h3 className="font-semibold text-green-700 mb-2">✓ You MAY use this service to:</h3>
                <ul className="space-y-1 ml-4 text-gray-600">
                  <li>• Learn how to structure BTEC assignments</li>
                  <li>• Understand what assessors are looking for</li>
                  <li>• Get inspiration for your own original writing</li>
                  <li>• Study examples of how to meet grading criteria</li>
                  <li>• Improve your academic writing skills</li>
                  <li>• Plan and outline your own assignments</li>
                </ul>
              </div>
              <div>
                <h3 className="font-semibold text-red-700 mb-2">✗ You must NOT use this service to:</h3>
                <ul className="space-y-1 ml-4 text-gray-600">
                  <li>• Submit generated content as your own work</li>
                  <li>• Bypass your institution's academic integrity policies</li>
                  <li>• Share content with others for direct submission</li>
                  <li>• Misrepresent AI-generated content as original work</li>
                </ul>
              </div>
            </div>
          </section>

          {/* Section 4: Disclaimer of Liability */}
          <section className="bg-white border-2 border-black rounded-xl p-4 sm:p-6 shadow-[4px_4px_0px_0px_rgba(0,0,0,1)]">
            <div className="flex items-center gap-3 mb-4">
              <div className="p-2 bg-red-100 rounded-lg border-2 border-black">
                <Scale className="w-5 h-5 text-red-600" />
              </div>
              <h2 className="text-lg sm:text-xl font-bold">4. Disclaimer of Liability</h2>
            </div>
            <div className="space-y-3 text-gray-700 text-sm sm:text-base">
              <p>
                BTEC Generator and its operators <strong>accept no responsibility</strong> for:
              </p>
              <ul className="space-y-2 ml-4">
                <li>• Any misuse of generated content by users</li>
                <li>• Academic consequences resulting from improper use of this service</li>
                <li>• Violations of institutional academic integrity policies</li>
                <li>• Any direct, indirect, or consequential damages arising from use of this service</li>
                <li>• The accuracy, completeness, or suitability of generated content</li>
              </ul>
              <div className="bg-red-50 border border-red-200 rounded-lg p-3 sm:p-4 mt-4">
                <p className="text-red-800 text-sm">
                  <strong>Important:</strong> You acknowledge that the decision to use generated content in any manner 
                  is entirely your own responsibility. Any consequences of such use, including but not limited to 
                  academic penalties, are solely your responsibility.
                </p>
              </div>
            </div>
          </section>

          {/* Section 5: Payment Terms */}
          <section className="bg-white border-2 border-black rounded-xl p-4 sm:p-6 shadow-[4px_4px_0px_0px_rgba(0,0,0,1)]">
            <div className="flex items-center gap-3 mb-4">
              <div className="p-2 bg-emerald-100 rounded-lg border-2 border-black">
                <Shield className="w-5 h-5 text-emerald-600" />
              </div>
              <h2 className="text-lg sm:text-xl font-bold">5. Payment Terms</h2>
            </div>
            <div className="space-y-3 text-gray-700 text-sm sm:text-base">
              <p>
                Access to BTEC Generator requires the purchase of tokens through our Discord bot system:
              </p>
              <ul className="space-y-2 ml-4">
                <li>• All payments are processed through <strong>peer-to-peer transfer</strong> to the displayed payment card</li>
                <li>• Payment verification is handled through our Discord bot</li>
                <li>• Tokens are non-refundable once purchased and verified</li>
                <li>• Token prices and plans are subject to change with notice</li>
                <li>• You are responsible for ensuring correct payment details before transfer</li>
              </ul>
              <div className="bg-emerald-50 border border-emerald-200 rounded-lg p-3 sm:p-4 mt-4">
                <p className="text-emerald-800 text-sm">
                  <strong>Note:</strong> We do not store your banking information. All payments are direct transfers 
                  that you initiate through your own banking app or service.
                </p>
              </div>
            </div>
          </section>

          {/* Section 6: Intellectual Property */}
          <section className="bg-white border-2 border-black rounded-xl p-4 sm:p-6 shadow-[4px_4px_0px_0px_rgba(0,0,0,1)]">
            <div className="flex items-center gap-3 mb-4">
              <div className="p-2 bg-indigo-100 rounded-lg border-2 border-black">
                <FileText className="w-5 h-5 text-indigo-600" />
              </div>
              <h2 className="text-lg sm:text-xl font-bold">6. Intellectual Property</h2>
            </div>
            <div className="space-y-3 text-gray-700 text-sm sm:text-base">
              <p>
                Content generated through BTEC Generator is provided for your personal educational use. However:
              </p>
              <ul className="space-y-2 ml-4">
                <li>• The BTEC Generator platform, branding, and interface remain our intellectual property</li>
                <li>• You may not redistribute, sell, or commercially exploit generated content</li>
                <li>• Generated content should be used as a learning tool, not a commercial product</li>
              </ul>
            </div>
          </section>

          {/* Section 7: Modifications */}
          <section className="bg-white border-2 border-black rounded-xl p-4 sm:p-6 shadow-[4px_4px_0px_0px_rgba(0,0,0,1)]">
            <div className="flex items-center gap-3 mb-4">
              <div className="p-2 bg-orange-100 rounded-lg border-2 border-black">
                <FileText className="w-5 h-5 text-orange-600" />
              </div>
              <h2 className="text-lg sm:text-xl font-bold">7. Modifications to Terms</h2>
            </div>
            <div className="space-y-3 text-gray-700 text-sm sm:text-base">
              <p>
                We reserve the right to modify these Terms of Use at any time. Changes will be effective immediately 
                upon posting to this page. Your continued use of the service after any modifications constitutes 
                acceptance of the revised terms.
              </p>
              <p>
                We encourage you to review these Terms periodically to stay informed of any updates.
              </p>
            </div>
          </section>

          {/* Section 8: Termination */}
          <section className="bg-white border-2 border-black rounded-xl p-4 sm:p-6 shadow-[4px_4px_0px_0px_rgba(0,0,0,1)]">
            <div className="flex items-center gap-3 mb-4">
              <div className="p-2 bg-gray-100 rounded-lg border-2 border-black">
                <AlertTriangle className="w-5 h-5 text-gray-600" />
              </div>
              <h2 className="text-lg sm:text-xl font-bold">8. Termination</h2>
            </div>
            <div className="space-y-3 text-gray-700 text-sm sm:text-base">
              <p>
                We reserve the right to terminate or suspend access to our service immediately, without prior notice, 
                for any reason including but not limited to:
              </p>
              <ul className="space-y-2 ml-4">
                <li>• Violation of these Terms of Use</li>
                <li>• Suspected fraudulent, abusive, or illegal activity</li>
                <li>• Any conduct that we determine, in our sole discretion, to be harmful to the service or other users</li>
              </ul>
            </div>
          </section>

          {/* Contact Section */}
          <section className="bg-gray-100 border-2 border-black rounded-xl p-4 sm:p-6">
            <h2 className="text-lg sm:text-xl font-bold mb-3">Contact Us</h2>
            <p className="text-gray-700 text-sm sm:text-base">
              If you have any questions about these Terms of Use, please contact us through our Discord server 
              or the Issue Reporting feature in your dashboard.
            </p>
          </section>
        </div>
      </main>

      {/* Footer */}
      <footer className="border-t-2 border-black mt-auto bg-white">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 py-6 sm:py-8 text-center">
          <div className="flex flex-wrap justify-center gap-2 sm:gap-4 text-xs sm:text-sm text-gray-600 mb-4">
            <button onClick={onBack} className="hover:text-black hover:underline">Dashboard</button>
            <span className="hidden sm:inline">•</span>
            <span className="text-black font-medium">Terms of Use</span>
            <span className="hidden sm:inline">•</span>
            <button onClick={() => onNavigate?.('privacy')} className="hover:text-black hover:underline">Privacy Policy</button>
            <span className="hidden sm:inline">•</span>
            <button onClick={() => onNavigate?.('disclaimer')} className="hover:text-black hover:underline">Academic Disclaimer</button>
          </div>
          <p className="text-xs text-gray-500">
            © {new Date().getFullYear()} BTEC Generator. All Rights Reserved.
          </p>
        </div>
      </footer>
    </div>
  );
}
